# Generated by Django 4.2 on 2023-04-10 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Cancelled', 'Cancelled')], default='Active', max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('is_renewal', models.BooleanField(default=False)),
                ('membership_type', models.CharField(choices=[('Student', 'Student'), ('Faculty', 'Faculty'), ('Alumni', 'Alumni')], default='Student', max_length=20)),
                ('max_books_allowed', models.PositiveSmallIntegerField(default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
