# Generated by Django 4.2 on 2023-04-11 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='quatity',
            new_name='quantity',
        ),
    ]
