# Generated by Django 4.2 on 2023-04-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the rack name', max_length=100)),
                ('location', models.CharField(help_text='Enter the location of the rack', max_length=100)),
                ('capacity', models.PositiveIntegerField(help_text='Enter the maximum number of books that can be stored in the rack')),
            ],
        ),
    ]
