# Generated by Django 4.2 on 2023-04-10 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_rack'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rack',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.rack'),
        ),
    ]
